import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SV Puschendorf Rasenturnier",
  description: "Generated by cedric",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* DEV-Hack: API-Schlüssel automatisch setzen im Entwicklungsmodus */}
        {process.env.NODE_ENV === 'development' && (
          <script src="/dev-api-hack.js" async></script>
        )}
      </body>
    </html>
  );
}
